### ISSUE TITLE
sequelize-cli is required but never mentioned

### ISSUE THREAD

**Issue by jordanrw** [GM456742/Passport_Tutorial#1]
`sequelize-cli` is needed during **step 6** for the command `sequelize init:models & sequelize init:config` to work. That isn't specified in **step 4** or anywhere else.

**Comment by GM456742** [comment]
Thank you @jordanrw  I have updated the readme to mention the cli. I assumed the reader only wants to know how to use PassportJs with their app but that was certainly a good point. I appreciate you having time to read through to make it better.

**Comment by jordanrw** [comment]
@GM456742 I appreciate the quick fix. Thank you so much for the tutorial! Before finding yours a friend actually mentioned to me how few resources there are for using Passport with a SQL server, so it's definitely needed.
